services:
  user-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: user-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-Str0ng!Passw0rd}
    ports: ["6001:1433"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 25
    volumes: ["user_data:/var/opt/mssql"]
    networks: [user-network]

  user-service:
    build:
      context: ./UserService
    container_name: user-service
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=user-db,1433;Database=UserDb;User Id=sa;Password=${SA_PASSWORD:-Str0ng!Passw0rd};TrustServerCertificate=True;      
      - Email__Username=${EMAIL__USERNAME}
      - Email__Password=${EMAIL__PASSWORD}
      - JwtSettings__Key=${JWTSETTINGS__KEY} 
      - JwtSettings__Issuer=${JWTSETTINGS__ISSUER} 
      - JwtSettings__Audience=${JWTSETTINGS__AUDIENCE} 
    depends_on:
      user-db:
        condition: service_healthy
    ports: ["5001:8080"]
    networks: [user-network, main-network]


  vocabulary-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: vocabulary-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-Str0ng!Passw0rd}
    ports: ["6002:1433"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 25
    volumes: ["vocabulary_data:/var/opt/mssql"]
    networks: [vocabulary-network]

  vocabulary-service:
    build:
      context: ./VocabularyService
    container_name: vocabulary-service
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=vocabulary-db,1433;Database=VocabularyDb;User Id=sa;Password=${SA_PASSWORD:-Str0ng!Passw0rd};TrustServerCertificate=True;
      - JwtSettings__Key=${JWTSETTINGS__KEY} 
      - JwtSettings__Issuer=${JWTSETTINGS__ISSUER} 
      - JwtSettings__Audience=${JWTSETTINGS__AUDIENCE} 
    depends_on:
      vocabulary-db:
        condition: service_healthy
    ports: ["5002:8080"]
    networks: [vocabulary-network, main-network]


  question-bank-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: question-bank-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-Str0ng!Passw0rd}
    ports: ["6003:1433"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 25
    volumes: ["question_bank_data:/var/opt/mssql"]
    networks: [question-bank-network]

  question-bank-service:
    build:
      context: ./QuestionBankService
    container_name: question-bank-service
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=question-bank-db,1433;Database=QuestionBankDb;User Id=sa;Password=${SA_PASSWORD:-Str0ng!Passw0rd};TrustServerCertificate=True;
      - JwtSettings__Key=${JWTSETTINGS__KEY} 
      - JwtSettings__Issuer=${JWTSETTINGS__ISSUER} 
      - JwtSettings__Audience=${JWTSETTINGS__AUDIENCE} 
    depends_on:
      question-bank-db:
        condition: service_healthy
    ports: ["5003:8080"]
    networks: [question-bank-network, main-network]


  roadmap-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: roadmap-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-Str0ng!Passw0rd}
    ports: ["6004:1433"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 25
    volumes: ["roadmap_data:/var/opt/mssql"]
    networks: [roadmap-network]

  roadmap-service:
    build:
      context: ./RoadmapService
    container_name: roadmap-service
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=roadmap-db,1433;Database=RoadmapDb;User Id=sa;Password=${SA_PASSWORD:-Str0ng!Passw0rd};TrustServerCertificate=True;
      - JwtSettings__Key=${JWTSETTINGS__KEY} 
      - JwtSettings__Issuer=${JWTSETTINGS__ISSUER} 
      - JwtSettings__Audience=${JWTSETTINGS__AUDIENCE} 
      - ServiceUrls__QuestionBank=http://question-bank-service:8080      
    depends_on:
      roadmap-db:
        condition: service_healthy
    ports: ["5004:8080"]
    networks: [roadmap-network, main-network]


  test-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: test-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-Str0ng!Passw0rd}
    ports: ["6005:1433"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 25
    volumes: ["test_data:/var/opt/mssql"]
    networks: [test-network]

  test-service:
    build:
      context: ./TestService
    container_name: test-service
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=test-db,1433;Database=TestDb;User Id=sa;Password=${SA_PASSWORD:-Str0ng!Passw0rd};TrustServerCertificate=True;
      - JwtSettings__Key=${JWTSETTINGS__KEY} 
      - JwtSettings__Issuer=${JWTSETTINGS__ISSUER} 
      - JwtSettings__Audience=${JWTSETTINGS__AUDIENCE} 
      - ApiSettings__BaseApiUrl=http://question-bank-service:8080/api # why don't you name it ServiceUrls__QuestionBank?
    depends_on:
      test-db:
        condition: service_healthy
    ports: ["5005:8080"]
    networks: [test-network, main-network]


  practice-service:
    build:
      context: ./PracticeService
    container_name: practice-service
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - JwtSettings__Key=${JWTSETTINGS__KEY} 
      - JwtSettings__Issuer=${JWTSETTINGS__ISSUER} 
      - JwtSettings__Audience=${JWTSETTINGS__AUDIENCE} 
      - ApiSettings__QuestionApiUrl=http://question-bank-service:8080/api # why don't you name it ServiceUrls__QuestionBank?
    depends_on:
      question-bank-service:
        condition: service_started
    ports: ["5006:8080"]
    networks: [main-network]
  

  apigateway:
    build:
      context: ./ApiGateway 
    container_name: apigateway
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      user-service: # 5001
        condition: service_started
      vocabulary-service: # 5002
        condition: service_started
      question-bank-service: # 5003
        condition: service_started
      roadmap-service: # 5004
        condition: service_started
      test-service: # 5005
        condition: service_started
      practice-service: # 5006
        condition: service_started
    ports: ["${GATEWAY_PORT}:8080"]
    networks: [main-network]

volumes:
  user_data:
  vocabulary_data:
  question_bank_data:
  roadmap_data:
  test_data:

networks:
  main-network:
    driver: bridge # liên kết các service với nhau và với apigateway
  user-network:
    driver: bridge # liên kết riêng user-db với user-service
  vocabulary-network:
    driver: bridge # liên kết riêng vocabulary-db với vocabulary-service
  question-bank-network:
    driver: bridge # liên kết riêng question-bank-db với question-bank-service
  roadmap-network:
    driver: bridge # liên kết riêng roadmap-db với roadmap-service
  test-network:
    driver: bridge # liên kết riêng test-db với test-service
  